server {
    listen 80 default_server;
    server_name saga.eb.mil.br 10.166.72.36 _;

    # Logs
    access_log /var/log/nginx/saga_access.log;
    error_log /var/log/nginx/saga_error.log;

    # Aumentar tamanhos de upload
    client_max_body_size 100M;

    location / {
        proxy_pass http://saga_app_dev:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Health check
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
